#!/usr/bin/env bash

function setup_util_firefox_dev() (
	source "$DOROTHY/sources/bash.bash"

	# setup
	local options=(
		--app='Mozilla Firefox Developer Edition'
		--cli='firefox-dev'
		"$@"
		CASK='firefox-developer-edition'
	)

	setup-util "${options[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_util_firefox_dev "$@"
fi
