#!/usr/bin/env bash

function setup_util_insomnia() (
	source "$DOROTHY/sources/bash.bash"

	# setup
	local options=(
		--app='Insomnia'
		--cli='insomnia'
		"$@"
		CASK='insomnia'
	)

	setup-util "${options[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_util_insomnia "$@"
fi
