#!/usr/bin/env bash

# https://github.com/99designs/aws-vault

function setup_util_aws_vault() (
	source "$DOROTHY/sources/bash.bash"

	# improve performance for detectable utilities with conditional assets
	if setup-util "$@" --check --cli=aws; then
		return 0
	fi

	# setup
	local options=(
		--cli='aws-vault'
		"$@"
		CASK='aws-vault'
	)

	setup-util "${options[@]}"
)

# fire if invoked standalone
if test "$0" = "${BASH_SOURCE[0]}"; then
	setup_util_aws_vault "$@"
fi
